### ISSUE TITLE
[BE] Implement `Community` submodule with Strapi

### ISSUE THREAD

**Issue by ddimkovikj** [learnhubmk/link-me#13]
UML diagram: https://github.com/learnhubmkd/link-me/wiki/Documentation#uml-diagram

- [ ] Map domain model 
- [ ] Map relations
- [ ] Implement API

**Comment by ddimkovikj** [comment]
Linking #6 as parent feature

**Comment by emorevival** [comment]
> UML diagram: https://excalidraw.com/#json=troy4rNx_r7aiR5Zlxf9B,p9WUh_3x4IRtqC9Tak9RYQ

are we going with the initial UML diagram or the revised one after the call? Because it's the old one for me when I follow the link

**Comment by ddimkovikj** [comment]
@emorevival updated the description with the new link. It appears that you need to regenerate it every time you make a change in Excalidraw.

**Comment by emorevival** [comment]
moving to dotnet
